### ISSUE TITLE
NoSuchMethodError using Cascade dynamic choice plugin

### ISSUE THREAD

**Issue by keiti** [biouno/uno-choice-plugin#45] opened 2014-11-07 09:57 UTC
See error below. I don´t think this depends on my settings, but here is my script:

if (binding.variables.get('Instanz') != null) {
  instanz= binding.variables.get('Instanz')
    if (instanz == 'QS') {
         return ['branches/Code/Migration-APFUmstellung-Trunk']
    } else {
        return ['DEV', 'TEST', 'TEST-INTEGRATION']
    }
} else {
  return []
}

HTTP ERROR 500

Problem accessing /job/Manual%20Deploy%20Client/configSubmit. Reason:

    org.apache.commons.lang.StringUtils.defaultIfBlank(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

Caused by:

java.lang.NoSuchMethodError: org.apache.commons.lang.StringUtils.defaultIfBlank(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at org.biouno.unochoice.CascadeChoiceParameterDefinition.<init>(CascadeChoiceParameterDefinition.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.kohsuke.stapler.RequestImpl.invokeConstructor(RequestImpl.java:441)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:387)
	at hudson.model.Descriptor.newInstance(Descriptor.java:549)
	at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:908)
	at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:896)
	at hudson.model.ParametersDefinitionProperty$DescriptorImpl.newInstance(ParametersDefinitionProperty.java:191)
	at hudson.model.Job.submit(Job.java:1551)
	at hudson.model.AbstractProject.submit(AbstractProject.java:2056)
	at hudson.model.BaseBuildableProject.submit(BaseBuildableProject.java:117)
	at hudson.model.FreeStyleProject.submit(FreeStyleProject.java:78)
	at hudson.model.Job.doConfigSubmit(Job.java:1480)
	at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:935)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:274)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:141)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:80)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:95)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:45)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:565)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:650)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:225)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:45)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:565)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:650)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:481)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:152)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:86)
	at org.hudsonci.servlets.internal.ServletRegistrationFilterAdapter.doFilter(ServletRegistrationFilterAdapter.java:162)
	at org.hudsonci.servlets.internal.ServletRegistrationFilterAdapter.doFilter(ServletRegistrationFilterAdapter.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:89)
	at org.hudsonci.servlets.internal.ServletRegistrationFilterAdapter.doFilter(ServletRegistrationFilterAdapter.java:162)
	at org.hudsonci.servlets.internal.ServletRegistrationFilterAdapter.doFilter(ServletRegistrationFilterAdapter.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:89)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:78)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:81)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:47)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:139)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:73)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:156)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:70)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:534)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:619)

Powered by Jetty://

**Comment by kinow** [comment] 2015-01-11 21:16
Hi @keiti, I'm not able to reproduce this issue in Jenkins. Closing it as we're preparing to cut a release to Jenkins update center. I don't believe we'll support Hudson, but please feel free to update this issue in case you find anything, or need some help.

**Closed by kinow** 2015-01-11 21:16 UTC
Labels: post_1.0
