### ISSUE TITLE
Using variables with Scriptler for Parameter Value 

### ISSUE THREAD

**Issue by christophdebaene** [biouno/uno-choice-plugin#43] opened 2014-11-04 10:25 UTC
Hi,

I am trying to pass a variable, which is already defined through a 'Uno-Choice Dynamic Choice Parameter' through another one using 'Uno-Choice Dynamic Choice Parameter (Scriptler)'. 

Without Scriptler you can get the variable by using binding.variables.get('SomeParameter') but how can it be passed through Scriptler?

Below you find a little example to illustrate the scenario.

![image](https://cloud.githubusercontent.com/assets/642207/4898045/3fb16e40-640c-11e4-9384-dd8dc6c575a2.png)

The 'Test' script itself is for example

![image](https://cloud.githubusercontent.com/assets/642207/4898067/74a1e88c-640c-11e4-841a-c82bc39a2817.png)

**Comment by kinow** [comment] 2015-01-11 21:23
Hi @christophdebaene ! Good news, we've been working on another issue that should fix this one too.

Take a look at issue #16, I'll leave this issue open while Ioannis is testing the issue's fix.

Thanks!

**Comment by imoutsatsos** [comment] 2015-01-12 21:53
+1 @kinow . This should fix it!

**Comment by christophdebaene** [comment] 2015-03-31 14:09
Great!
Is the new version already available through the updates (plugin) in Jenkins?

**Comment by kinow** [comment] 2015-03-31 14:27
Hi @christophdebaene, the new version (0.24) is available through our update center and should contain the fix for this issue. However, third party update sites are not working in recent versions of Jenkins (working on it). 

It would be great if you could chime in in the thread with the proposal to release this plug-in through the update center https://groups.google.com/forum/#!topic/jenkinsci-dev/qUBLhE-4ybY

We have several users now, scientists and researchers, but also devops/programmers/ops and others. So I still believe it makes sense to publish the uno choice plugin via Jenkins UC, even if for that we have to rename it.

**Comment by christophdebaene** [comment] 2015-06-03 13:51
I have noticed that the plugin has been renamed to [Active Choices Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Active+Choices+Plugin). Is there a way to test the plugin? In jenkins I added http://biouno.org/jenkins-update-site.html but is doesn't appear in the list.

**Comment by kinow** [comment] 2015-06-03 23:36
Hi @christophdebaene 

We have released the 1.0 version to all users last night.

https://groups.google.com/forum/#!topic/biouno-users/pR6ZrFQqE80

**Comment by kinow** [comment] 2015-06-04 02:44
Closing. If the issue is still happening in Active Choices 1.0, please feel free to file a new issue to https://issues.jenkins-ci.org, component = active-choices-plugin :-) Thanks!

**Closed by kinow** 2015-06-04 02:44 UTC
Labels: post_1.0, waiting for feedback, wontfix
