### ISSUE TITLE
Uno-choice reference parameter unusable

### ISSUE THREAD

**Issue by gabre** [biouno/uno-choice-plugin#77] opened 2015-04-07 10:11 UTC
I would like to do the following:
 1, create a single-selection menu
 2, depending on the value of the single-selection menu I would like to generate a form with HTML (e.g. if the value is "A" I would like to generate radio button; if the value is "B" I would like to generate two input fields and a checkbox)
I cannot use the values of the widgets of the form.

1, Is it possible to create such a behaviour using this plugin?
2, If yes, how? Could you provide some deeper tutorial?
3, If no, can it be implemented somehow?

**Comment by gabre** [comment] 2015-04-07 10:15
I cannot use the values of the widgets of the form. <- I mean the values of the GENERATED widgets (given with html)

**Comment by imoutsatsos** [comment] 2015-04-07 11:18
@gabre You have correctly pointed out that values from UC dynamic references are not typically passed to the build. This is by design. UC Dynamic References were designed to just assist you in making decisions about other parameters on the build form. 

However, there is an exception to this. See this wiki page for additional details: https://github.com/biouno/uno-choice-plugin/wiki/Using-Uno-Choice-for-Dynamic-Input-Text-Box-Defaults

Essentially, if you setup your returned Dynamic Reference as formatted input, then the value can be passed to the build (and this value can be hidden). Finally make sure to check under 'Advanced' options the 'Omit value field' option to allow YOUR value rather than the default to propagate to the build.

If there are multiple Dynamic References on the page you may want to aggregate their values in a hidden Dynamic Reference and then pass this to the build. So for the example you requested above, you could create a hidden dynamic reference (input type) variable from the checkbox and the two input fields and then parse it in your code to retrieve all 3 variables into the build. I envision it would look something like 'true:Input1:Input2'

Hope these ideas give you a starting point. Once you get how reference parameter works you'l come with additional ideas on how to use it on your own.

Best regards
Ioannis

**Comment by kinow** [comment] 2015-06-04 03:12
Closing as version 1.0 has been released in Jenkins update center. Please feel free to move the conversation to https://issues.jenkins-ci.org, component = active-choices-plugin. Thanks!

**Closed by kinow** 2015-06-04 03:12 UTC
