### ISSUE TITLE
Getting "Signature verification failed in update site 'biouno-update-center' "

### ISSUE THREAD

**Issue by murarisumit** [biouno/uno-choice-plugin#76] opened 2015-03-13 05:38 UTC
I've followed the steps given in "http://biouno.org/jenkins-update-site.html"
After updated the plugin, got this error ==> " Signature verification failed in update site 'biouno-update-center' "

What am I missing..?

**Comment by kinow** [comment] 2015-03-13 23:36
Hi @murarisumit, did you check that you needed a certificate, and included the certificate provided in the site that you mentioned? I'm going to quickly set up a test env to give it a try.

**Comment by kinow** [comment] 2015-03-13 23:42
Issue reproduced. I will check if something changed in the update center server. Thanks for reporting! :)

**Comment by kinow** [comment] 2015-03-14 00:21
Tried with LTS too, looks like there are similar issues already in Jenkins JIRA:

https://issues.jenkins-ci.org/browse/JENKINS-13498

**Comment by imoutsatsos** [comment] 2015-03-20 20:31
Same here using Jenkins v 1.596.1. This is the log output:
```
Mar 20, 2015 4:24:59 PM INFO hudson.model.UpdateSite updateData
Obtained the latest update center data file for UpdateSource default
Mar 20, 2015 4:24:59 PM SEVERE hudson.model.UpdateSite updateData
ERROR: Signature verification failed in update site &#039;biouno-update-center&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
	at java.security.cert.CertPathValidator.validate(Unknown Source)
	at org.jvnet.hudson.crypto.CertificateUtil.validatePath(CertificateUtil.java:93)
	at jenkins.util.JSONSignatureValidator.verifySignature(JSONSignatureValidator.java:76)
	at hudson.model.UpdateSite.verifySignature(UpdateSite.java:227)
	at hudson.model.UpdateSite.updateData(UpdateSite.java:206)
	at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:178)
	at hudson.PluginManager.doCheckUpdatesServer(PluginManager.java:890)
	at jenkins.model.DownloadSettings$DailyCheck.execute(DownloadSettings.java:118)
	at hudson.model.AsyncPeriodicWork$1.run(AsyncPeriodicWork.java:53)
	at java.lang.Thread.run(Unknown Source)
</pre>
```

**Comment by kinow** [comment] 2015-03-20 22:29
Thanks for the feedback @imoutsatsos ! I'll investigate this issue during this weekend. Hopefullly by Monday everything will be working again :-)

**Comment by kinow** [comment] 2015-03-24 00:02
Works with Jenkins 1.580. Looks like something changed in UpdateSite. I'm using [this baseline](https://github.com/jenkinsci/jenkins/blob/jenkins-1.580/core/src/main/java/hudson/model/UpdateSite.java) to compare with other branches/tags. 

A work around is copy the Update Center's certificate to a path within $JENKINS_HOME/war/WEB-INF/. But I prefer to fix the issue instead of teaching users how to fix it temporarily. My guess is that the issue can be fixed by 1) fixing something in Jenkins core or 2) fixing something in ikedam's UpdateSites Manager Plug-in

**Comment by imoutsatsos** [comment] 2015-03-24 00:55
oh me too! I prefer a fix but sometimes you have to apply a workaround...

**Comment by devgeek578** [comment] 2015-03-26 18:21
Any update on this issue? I am evaluating Jenkins for my company and have been researching for days on a way to tackle an issue that I've ran into and it looks like the uno-choice-plugin will work perfectly, but I cannot install the plugin because I am unable to install biouno update site.

**Comment by imoutsatsos** [comment] 2015-03-26 18:55
@devgeek578 Glad you found the link. Let us know if you need any assistance in using the plugin.

**Comment by kinow** [comment] 2015-03-27 00:02
@devgeek578 once I get some a couple of days to work on this issue, as well as lots of coffee to debug Jenkins and the UpdateSites Manager, I'll try to take on this issue and make our Update Center available again.

**Comment by devgeek578** [comment] 2015-03-27 00:35
Awesome,  thanks! Your plugin worked like a charm btw;)

**Comment by kinow** [comment] 2015-03-27 01:28
Thanks to all great feedback, bug reports, testing and help provided by its community (including you), and @imoutsatsos feature guidance and thorough testing :-) Let us know if you need anything else.

**Comment by imoutsatsos** [comment] 2015-04-13 13:19
@kinow has now posted a workaround to this issue. Please see the discussion on the BioUno users forum: https://groups.google.com/d/msg/biouno-users/-K7Xf5mtpeg/HXsjW6EvkuEJ

**Comment by kinow** [comment] 2015-06-04 03:11
Version 1.0 has been released to Jenkins update center. Closing.

**Closed by kinow** 2015-06-04 03:11 UTC
